/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MyPoolsRouteImport } from './routes/my-pools'
import { Route as PoolIdIndexRouteImport } from './routes/pool.$id.index'
import { Route as PoolIdAdminRouteImport } from './routes/pool.$id.admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPoolsRoute = MyPoolsRouteImport.update({
  id: '/my-pools',
  path: '/my-pools',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolIdIndexRoute = PoolIdIndexRouteImport.update({
  id: '/pool/$id/',
  path: '/pool/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolIdAdminRoute = PoolIdAdminRouteImport.update({
  id: '/pool/$id/admin',
  path: '/pool/$id/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/my-pools': typeof MyPoolsRoute
  '/pool/$id/admin': typeof PoolIdAdminRoute
  '/pool/$id/': typeof PoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/my-pools': typeof MyPoolsRoute
  '/pool/$id/admin': typeof PoolIdAdminRoute
  '/pool/$id': typeof PoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/my-pools': typeof MyPoolsRoute
  '/pool/$id/admin': typeof PoolIdAdminRoute
  '/pool/$id/': typeof PoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/how-it-works'
    | '/my-pools'
    | '/pool/$id/admin'
    | '/pool/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/how-it-works'
    | '/my-pools'
    | '/pool/$id/admin'
    | '/pool/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/how-it-works'
    | '/my-pools'
    | '/pool/$id/admin'
    | '/pool/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MyPoolsRoute: typeof MyPoolsRoute
  PoolIdAdminRoute: typeof PoolIdAdminRoute
  PoolIdIndexRoute: typeof PoolIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pools': {
      id: '/my-pools'
      path: '/my-pools'
      fullPath: '/my-pools'
      preLoaderRoute: typeof MyPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/$id/': {
      id: '/pool/$id/'
      path: '/pool/$id'
      fullPath: '/pool/$id/'
      preLoaderRoute: typeof PoolIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/$id/admin': {
      id: '/pool/$id/admin'
      path: '/pool/$id/admin'
      fullPath: '/pool/$id/admin'
      preLoaderRoute: typeof PoolIdAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  HowItWorksRoute: HowItWorksRoute,
  MyPoolsRoute: MyPoolsRoute,
  PoolIdAdminRoute: PoolIdAdminRoute,
  PoolIdIndexRoute: PoolIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
